name: Android CI Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.21.1'

      - name: Install Dependencies
        run: npm install

      - name: Setup Java (JDK 17)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Give Gradle Permission
        run: chmod +x android/gradlew

      - name: Build Android APK
        run: cd android && ./gradlew assembleRelease

      - name: Get current date
        id: date
        run: echo "DATE=$(date +'%d%m%Y')" >> $GITHUB_ENV

      - name: Rename APK
        run: mv android/app/build/outputs/apk/release/app-release.apk android/app/build/outputs/apk/release/rnbridge-${{ env.DATE }}.apk

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
        name: rnbridge-${{ env.DATE }}
        path: android/app/build/outputs/apk/release/rnbridge-${{ env.DATE }}.apk